import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Bar from "./header/bar/Bar";
import Footer from "./header/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-[100vh]">
          <Bar />
          <main>{children}</main>
          <footer className="mt-auto ">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
